# Generated by Django 5.0.4 on 2024-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FerrumMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Текст')),
                ('data', models.DateField(verbose_name='Дата Публикации')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыка',
            },
        ),
    ]
